[env:esp32dev]
platform = espressif32
board    = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

; Chỉ khai báo các thư viện thực sự được dùng trong code
lib_deps =
    knolleary/PubSubClient@^2.8        ; MQTT client
    adafruit/DHT sensor library@^1.4.4 ; Cảm biến DHT11/DHT22
    bblanchon/ArduinoJson@^7.0.4       ; Xử lý JSON
